2024-10-04 09:07:25,886 INFO    MainThread:31836 [wandb_setup.py:_flush():77] Current SDK version is 0.17.8
2024-10-04 09:07:25,886 INFO    MainThread:31836 [wandb_setup.py:_flush():77] Configure stats pid to 31836
2024-10-04 09:07:25,887 INFO    MainThread:31836 [wandb_setup.py:_flush():77] Loading settings from C:\Users\pink\.config\wandb\settings
2024-10-04 09:07:25,887 INFO    MainThread:31836 [wandb_setup.py:_flush():77] Loading settings from C:\Users\pink\Documents\Study\Intelligent Systems\COS30018-Mitigate-Hallucination\wandb\settings
2024-10-04 09:07:25,887 INFO    MainThread:31836 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-10-04 09:07:25,887 INFO    MainThread:31836 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-10-04 09:07:25,887 INFO    MainThread:31836 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'Finetuning\\LLAMA3_QLoRA.py', 'program_abspath': 'c:\\Users\\pink\\Documents\\Study\\Intelligent Systems\\COS30018-Mitigate-Hallucination\\Finetuning\\LLAMA3_QLoRA.py', 'program': 'c:\\Users\\pink\\Documents\\Study\\Intelligent Systems\\COS30018-Mitigate-Hallucination\\Finetuning\\LLAMA3_QLoRA.py'}
2024-10-04 09:07:25,887 INFO    MainThread:31836 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-10-04 09:07:25,887 INFO    MainThread:31836 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\pink\Documents\Study\Intelligent Systems\COS30018-Mitigate-Hallucination\wandb\run-20241004_090725-us1gaq1d\logs\debug.log
2024-10-04 09:07:25,887 INFO    MainThread:31836 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\pink\Documents\Study\Intelligent Systems\COS30018-Mitigate-Hallucination\wandb\run-20241004_090725-us1gaq1d\logs\debug-internal.log
2024-10-04 09:07:25,888 INFO    MainThread:31836 [wandb_init.py:init():607] calling init triggers
2024-10-04 09:07:25,888 INFO    MainThread:31836 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-10-04 09:07:25,888 INFO    MainThread:31836 [wandb_init.py:init():657] starting backend
2024-10-04 09:07:25,888 INFO    MainThread:31836 [wandb_init.py:init():661] setting up manager
2024-10-04 09:07:25,890 INFO    MainThread:31836 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-10-04 09:07:25,892 INFO    MainThread:31836 [wandb_init.py:init():669] backend started and connected
2024-10-04 09:07:25,894 INFO    MainThread:31836 [wandb_init.py:init():767] updated telemetry
2024-10-04 09:07:25,917 INFO    MainThread:31836 [wandb_init.py:init():800] communicating run to backend with 90.0 second timeout
2024-10-04 09:07:44,094 WARNING MainThread:31836 [wandb_init.py:init():1232] interrupted
Traceback (most recent call last):
  File "C:\Users\pink\anaconda3\envs\LLama3-hallucinate\Lib\site-packages\wandb\sdk\wandb_init.py", line 1228, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\pink\anaconda3\envs\LLama3-hallucinate\Lib\site-packages\wandb\sdk\wandb_init.py", line 803, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pink\anaconda3\envs\LLama3-hallucinate\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pink\anaconda3\envs\LLama3-hallucinate\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pink\anaconda3\envs\LLama3-hallucinate\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pink\anaconda3\envs\LLama3-hallucinate\Lib\threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pink\anaconda3\envs\LLama3-hallucinate\Lib\threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-10-04 09:07:50,363 WARNING MsgRouterThr:31836 [router.py:message_loop():77] message_loop has been closed
